spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: ${APPLICATION_NAME}
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: ${DB_DRIVER}
    jpa:
        hibernate:
            ddl-auto: ${HIBERNATE_DDL}
        show-sql: ${JPA_SHOW_SQL}
        properties:
            hibernate:
                fomrat-sql: ${HIBERNATE_FORMAT_SQL}
        database: ${DATABASE}
        database-platform: ${HIBERNATE_DIALECT}
